### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by raju249**
Add Azure VM Unit tests.
This completes Phase 1 work.

### CODE REVIEW

**Comment by raju249** [comment]
@rajikaimal 
@rehrumesh 
Request to review this PR.

**Comment by rajikaimal** [comment]
Please rename `_` in to `-`.

**Comment by raju249** [comment]
Yes,that's tracked in other issue. Will be doing for all files at once.

**Comment by rajikaimal** [comment]
Ok got it.

**Comment by raju249** [comment]
@rajikaimal 
Conflicts are fixed. Please review.
Thanks

**Pull request merged**
